export const FETCH_USERS_REQUST = "FETCH_USERS_REQUST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCES";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const DELETE_USER_REQUST = "DELETE_USER_REQUST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
